[logging]
"console level" = "INFO"
"file level" = "INFO"

[modules]
deliver = [
    "git",
]

[git]
directory = "hworker_personal"

[git.users]
Me = "https://github.com/maryhaidei/Practice-321.git"
Him = "https://github.com/NikitM1/Practice3.git"

[imap]
host = "host"
port = 993
folder = "INBOX"
username = "username"
password = "password"
letter_limit = -1

[imap.users]

[file]
root_path = "files"

[file.users]

[tasks."20240910/1"]
open_date = 2024-09-10 01:00:00
deliver_ID = "20240910/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-16 01:00:00
hard_deadline = 2024-09-23 01:00:00

[tasks."20240917/1"]
open_date = 2024-09-17 01:00:00
deliver_ID = "20240917/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-23 01:00:00
hard_deadline = 2024-09-30 01:00:00

[tasks."20240917/2"]
open_date = 2024-09-17 01:00:00
deliver_ID = "20240917/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-23 01:00:00
hard_deadline = 2024-09-30 01:00:00

[tasks."20240917/3"]
open_date = 2024-09-17 01:00:00
deliver_ID = "20240917/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-23 01:00:00
hard_deadline = 2024-09-30 01:00:00

[tasks."20240924/1"]
open_date = 2024-09-24 01:00:00
deliver_ID = "20240924/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-30 01:00:00
hard_deadline = 2024-10-07 01:00:00

[tasks."20240924/2"]
open_date = 2024-09-24 01:00:00
deliver_ID = "20240924/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-30 01:00:00
hard_deadline = 2024-10-07 01:00:00

[tasks."20240924/3"]
open_date = 2024-09-24 01:00:00
deliver_ID = "20240924/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-09-30 01:00:00
hard_deadline = 2024-10-07 01:00:00

[tasks."20241001/1"]
open_date = 2024-10-01 01:00:00
deliver_ID = "20241001/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-07 01:00:00
hard_deadline = 2024-10-14 01:00:00

[tasks."20241001/2"]
open_date = 2024-10-01 01:00:00
deliver_ID = "20241001/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-07 01:00:00
hard_deadline = 2024-10-14 01:00:00

[tasks."20241001/3"]
open_date = 2024-10-01 01:00:00
deliver_ID = "20241001/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-07 01:00:00
hard_deadline = 2024-10-14 01:00:00

[tasks."20241008/1"]
open_date = 2024-10-08 01:00:00
deliver_ID = "20241008/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-14 01:00:00
hard_deadline = 2024-10-21 01:00:00

[tasks."20241008/2"]
open_date = 2024-10-08 01:00:00
deliver_ID = "20241008/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-14 01:00:00
hard_deadline = 2024-10-21 01:00:00

[tasks."20241008/3"]
open_date = 2024-10-08 01:00:00
deliver_ID = "20241008/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-14 01:00:00
hard_deadline = 2024-10-21 01:00:00

[tasks."20241015/1"]
open_date = 2024-10-15 01:00:00
deliver_ID = "20241015/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-21 01:00:00
hard_deadline = 2024-10-28 01:00:00

[tasks."20241015/2"]
open_date = 2024-10-15 01:00:00
deliver_ID = "20241015/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-21 01:00:00
hard_deadline = 2024-10-28 01:00:00

[tasks."20241015/3"]
open_date = 2024-10-15 01:00:00
deliver_ID = "20241015/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-21 01:00:00
hard_deadline = 2024-10-28 01:00:00

[tasks."20241022/1"]
open_date = 2024-10-22 01:00:00
deliver_ID = "20241022/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-28 01:00:00
hard_deadline = 2024-11-04 01:00:00

[tasks."20241022/2"]
open_date = 2024-10-22 01:00:00
deliver_ID = "20241022/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-28 01:00:00
hard_deadline = 2024-11-04 01:00:00

[tasks."20241022/3"]
open_date = 2024-10-22 01:00:00
deliver_ID = "20241022/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-10-28 01:00:00
hard_deadline = 2024-11-04 01:00:00

[tasks."20241105/1"]
open_date = 2024-11-05 01:00:00
deliver_ID = "20241105/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-11 01:00:00
hard_deadline = 2024-11-18 01:00:00

[tasks."20241105/2"]
open_date = 2024-11-05 01:00:00
deliver_ID = "20241105/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-11 01:00:00
hard_deadline = 2024-11-18 01:00:00

[tasks."20241105/3"]
open_date = 2024-11-05 01:00:00
deliver_ID = "20241105/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-11 01:00:00
hard_deadline = 2024-11-18 01:00:00

[tasks."20241112/1"]
open_date = 2024-11-12 01:00:00
deliver_ID = "20241112/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-18 01:00:00
hard_deadline = 2024-11-25 01:00:00

[tasks."20241112/2"]
open_date = 2024-11-12 01:00:00
deliver_ID = "20241112/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-18 01:00:00
hard_deadline = 2024-11-25 01:00:00

[tasks."20241112/3"]
open_date = 2024-11-12 01:00:00
deliver_ID = "20241112/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-18 01:00:00
hard_deadline = 2024-11-25 01:00:00

[tasks."20241119/1"]
open_date = 2024-11-19 01:00:00
deliver_ID = "20241119/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-25 01:00:00
hard_deadline = 2024-12-02 01:00:00

[tasks."20241119/2"]
open_date = 2024-11-19 01:00:00
deliver_ID = "20241119/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-25 01:00:00
hard_deadline = 2024-12-02 01:00:00

[tasks."20241119/3"]
open_date = 2024-11-19 01:00:00
deliver_ID = "20241119/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-11-25 01:00:00
hard_deadline = 2024-12-02 01:00:00

[tasks."20241126/1"]
open_date = 2024-11-26 01:00:00
deliver_ID = "20241126/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-02 01:00:00
hard_deadline = 2024-12-09 01:00:00

[tasks."20241126/2"]
open_date = 2024-11-26 01:00:00
deliver_ID = "20241126/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-02 01:00:00
hard_deadline = 2024-12-09 01:00:00

[tasks."20241126/3"]
open_date = 2024-11-26 01:00:00
deliver_ID = "20241126/3"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-02 01:00:00
hard_deadline = 2024-12-09 01:00:00

[tasks."20241203/1"]
open_date = 2024-12-03 01:00:00
deliver_ID = "20241203/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-09 01:00:00
hard_deadline = 2024-12-16 01:00:00

[tasks."20241203/2"]
open_date = 2024-12-03 01:00:00
deliver_ID = "20241203/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-09 01:00:00
hard_deadline = 2024-12-16 01:00:00

[tasks."20241210/1"]
open_date = 2024-12-10 01:00:00
deliver_ID = "20241210/1"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-16 01:00:00
hard_deadline = 2024-12-23 01:00:00

[tasks."20241210/2"]
open_date = 2024-12-10 01:00:00
deliver_ID = "20241210/2"
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 1024
time_limit = 2
resource_limit = 3145728
soft_deadline = 2024-12-16 01:00:00
hard_deadline = 2024-12-23 01:00:00

[make]
screenreplay = false
deadline_gap = 03:00:00

[check]
directory = "hworker_check"
user_checks = true

[formalization]
prog_name = "prog.py"
remote_name = "remote"
check_name = "check"
runtime_suffix = [
    "in",
    "out",
]
validate_suffix = "py"
validator_name = "validator"
version_validator_name = "version_validator"
no_merge = [
    "checks",
]

[publish]
host = "0.0.0.0"
port = "8080"
course_name = "My prac"
secret_cookie = "kapibara"
static_folder = "static"
url_prefix = ""
SECRET_KEY = "8556aa9cfdd8c8e0884d1b2568985789372281093f338caf5cc145fdb9e5f7b5"

[score]
score_directory = "scores"

[depot]
database_path = "data.db"
